### ISSUE TITLE
Refused to fetch content from '<DOMAIN>:443/static/assets/index-3a79bbc9.js' because it violates the following Content Security Policy directive: "default-src 'self' <DOMAIN>:443".

### ISSUE THREAD

**Issue by utdelsec** [vicalloy/outline-docker-compose#76]
Hi,

I have configured the docker container to expose 443 port for https and now can access the admin page over HTTPS, however when I try to access outline, I get the following error:

`Refused to fetch content from '<DOMAIN>:443/static/assets/index-3a79bbc9.js' because it violates the following Content Security Policy directive: "default-src 'self' <DOMAIN>:443".`

There are no modifications in the config file except for 

```
wk-nginx:
    image: nginx
    ports:
      - ${HTTP_IP}:${HTTP_PORT_IP}:80
      - ${HTTPS_IP}:${HTTPS_PORT_IP}:443
    volumes:
      - ./config/nginx/:/etc/nginx/conf.d/:ro
      - ./data/uc/static_root:/uc/static_root:ro
      - /etc/certs/ssl_cert.cer:/etc/certs/ssl_cert.cer:ro
      - /etc/certs/ssl_cert.key:/etc/certs/ssl_cert.key:ro
```
I have been playing with nginx add_headers but so far nothing has worked. Please help me.
